### ISSUE TITLE
Is it possible to add for other countries?

### ISSUE THREAD

**Issue by templatetuners** [Magisk-Modules-Repo/volte-kr-crosshatch#3]
Hi, I need to activate volte and wifi call on pixel 2 XL. My carrier activated the services but phone's toggle still can't be turned on :(
Can this be updated for multiple devices and carriers? 
Thanks.

**Comment by nooriro** [comment]
It will be difficult for me to work on it myself because I can't test VoLTE in your situation. First, I don't have a Pixel 2 or Pixel 2 XL. Second, I live in South Korea.

I know little about Pixel 2. However, Pixel 2 is likely to be VoLTE enabled in a similar way to Pixel 3, since  its `modem` partition contains only __modem firmware__ and  __carrier-specific modem config__ (`mcfg_sw.mbn`) files are located somewhere (which is different from the path on Pixel 3) in the `vendor` partition.

On pixel 3, running `rm /data/vendor/modem_fdr/fdr_check && reboot` command in shell, with root privileges, refreshes the modem settings after reboot. Like this, if you can figure out how to trigger refreshing modem settings on Pixel 2, systemlessly VoLTE activation will be possible on Pixel 2.

**Comment by nooriro** [comment]
See the xda thread as well :
https://forum.xda-developers.com/pixel-2/how-to/guide-enable-volte-unsupported-carriers-t3892659

**Comment by templatetuners** [comment]
VoEnabler is deprecated.
I dont have `modem_fdr` in `vendor` but I found in `vendor\mbn\mcfg\configs\mcfg_sw` this `oem_sw.txt `
```
mcfg_sw/generic/NA/ATT/VoLTE/mcfg_sw.mbn
mcfg_sw/generic/NA/Cricket/VoLTE/mcfg_sw.mbn
mcfg_sw/generic/NA/Sprint/Commercial/mcfg_sw.mbn
mcfg_sw/generic/NA/TMO/Commercial/mcfg_sw.mbn
mcfg_sw/generic/NA/Verizon/hVoLTE/mcfg_sw.mbn
mcfg_sw/generic/EU/EE/Commercial/mcfg_sw.mbn
mcfg_sw/generic/EU/DT/VoLTE/Commercial/mcfg_sw.mbn
mcfg_sw/generic/EU/Telefonica/Commercial/DE/mcfg_sw.mbn
mcfg_sw/generic/EU/Vodafone/VoLTE/Germany/mcfg_sw.mbn
mcfg_sw/generic/common/WildCard/WildCard/mcfg_sw.mbn
mcfg_sw/generic/NA/Bell/VoLTE/mcfg_sw.mbn
mcfg_sw/generic/NA/ROGERS/Commercial/mcfg_sw.mbn
mcfg_sw/generic/NA/Telus/VoLTE/mcfg_sw.mbn
mcfg_sw/generic/EU/H3G/VoLTE/UK/mcfg_sw.mbn
mcfg_sw/generic/AUS/Telstra/VoLTE/mcfg_sw.mbn
mcfg_sw/generic/NA/USCC/Commercial/mcfg_sw.mbn
mcfg_sw/generic/APAC/Reliance/Commercial/mcfg_sw.mbn
mcfg_sw/generic/EU/Vodafone/VoLTE/UK/mcfg_sw.mbn
mcfg_sw/generic/NA/Freedom/VoLTE/mcfg_sw.mbn
mcfg_sw/generic/NA/Videotron/non_VoLTE/mcfg_sw.mbn
mcfg_sw/generic/EU/Vodafone/Lab/VoLTE/Germany/mcfg_sw.mbn
mcfg_sw/generic/AUS/Default/VoLTE/mcfg_sw.mbn
mcfg_sw/generic/EU/Telefonica/Non_VoLTE/UK/mcfg_sw.mbn
mcfg_sw/generic/EU/ID/Non_VoLTE/UK/mcfg_sw.mbn
mcfg_sw/generic/NA/Koodo/non_VoLTE/mcfg_sw.mbn
mcfg_sw/generic/common/PixelLite/Commercial/mcfg_sw.mbn
```
There is a way to open .mbm files?

**Comment by templatetuners** [comment]
Installed **VoEnabler** and now I have all of them active under ***#*#4636#*#*** and in phone's menu like wifi call/video call cant be activated in settings and assisted dialing doesnt show noting
none of them works.

**Comment by nooriro** [comment]
> There is a way to open .mbm files?

I have never seen such a way.

Formally, `mcfg_sw.mbn` is an ELF file.

```
nooriro@xps:/mnt/c/Users/nooriro/Desktop/mbn/mcfg_sw/generic/Korea/LGU/Commercial$ readelf -h -l mcfg_sw.mbn
ELF Header:
  Magic:   7f 45 4c 46 01 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF32
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           None
  Version:                           0x1
  Entry point address:               0x0
  Start of program headers:          52 (bytes into file)
  Start of section headers:          0 (bytes into file)
  Flags:                             0x5
  Size of this header:               52 (bytes)
  Size of program headers:           32 (bytes)
  Number of program headers:         3
  Size of section headers:           40 (bytes)
  Number of section headers:         0
  Section header string table index: 0

Program Headers:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  NULL           0x000000 0x00000000 0x00000000 0x00094 0x00000     0
  NULL           0x001000 0x00007000 0x00007000 0x00088 0x01000     0x1000
  LOAD           0x002000 0x00000000 0x00000000 0x06664 0x06664 RW  0x4
nooriro@xps:/mnt/c/Users/nooriro/Desktop/mbn/mcfg_sw/generic/Korea/LGU/Commercial$
```

__NV data__ (__files__ and __item files__) to be loaded into EFS (`modemst1` and `modemst2` partitions) are stored starting from __offset 0x2000__.

![mbn_hxd_02_20190608](https://user-images.githubusercontent.com/16160401/59142989-2c0a8c80-8a01-11e9-917c-3c185058b78e.png)

Unfortunately, not only the format of each NV item but also the format which these NV data are stored in `mcfg_sw.mbn` is not available on the web, since Qualcomm does not open the format. If you do some __reverse-engineering with QPST EFS Explorer__, maybe you can create a tool to parse  `mcfg_sw.mbn`.  But it's not easy to ensure the reliability of the tool.

**Comment by nooriro** [comment]
> Installed **VoEnabler** and now I have all of them active under ___#_#4636#_#_** and in phone's menu like wifi call/video call cant be activated in settings and assisted dialing doesnt show noting
> none of them works.

Sorry, but I do not know anything about video calls and VoWiFi.
